'use client'

import { useCallback, useRef, useState } from 'react'
import { filenameFromDisposition } from '@/lib/resume/export/filename'

/**
 * Download PDF.
 *
 * The file is generated by the server, from the stored resume. This component
 * sends one id and receives bytes -- it never builds HTML, never names the
 * file, and never decides what the document contains. The filename comes from
 * the response's Content-Disposition, which the route sanitises; constructing
 * one here would duplicate that sanitisation and eventually diverge from it.
 *
 * Cold-starting Chromium takes seconds, so the pending state is not decoration:
 * without it a person clicks twice and waits for two exports.
 */

const ENDPOINT = '/api/resume-v2/export/pdf'

type State =
  | { readonly kind: 'idle' }
  | { readonly kind: 'working' }
  | { readonly kind: 'failed'; readonly message: string }

export default function DownloadPdfButton({
  resumeId,
  disabled,
}: {
  resumeId: string
  disabled?: boolean
}) {
  const [state, setState] = useState<State>({ kind: 'idle' })
  const inFlight = useRef(false)

  const download = useCallback(async () => {
    if (inFlight.current) return
    inFlight.current = true
    setState({ kind: 'working' })

    let objectUrl: string | null = null
    try {
      const res = await fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: resumeId }),
      })

      if (!res.ok) {
        setState({ kind: 'failed', message: messageFor(res.status) })
        return
      }

      const blob = await res.blob()
      const filename = filenameFromDisposition(res.headers.get('Content-Disposition'))

      objectUrl = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = objectUrl
      link.download = filename
      document.body.appendChild(link)
      link.click()
      link.remove()
      setState({ kind: 'idle' })
    } catch {
      setState({ kind: 'failed', message: 'Could not reach the server.' })
    } finally {
      // Revoked later, not synchronously: revoking immediately can cancel the
      // download in Safari before it has finished reading the blob.
      if (objectUrl) {
        const url = objectUrl
        setTimeout(() => URL.revokeObjectURL(url), 30_000)
      }
      inFlight.current = false
    }
  }, [resumeId])

  const working = state.kind === 'working'

  return (
    <div className="flex flex-col items-start sm:items-end gap-1">
      <button
        type="button"
        onClick={() => void download()}
        disabled={working || disabled}
        aria-busy={working}
        className="px-4 py-2 text-sm font-semibold rounded-xl bg-white text-indigo-900 hover:bg-indigo-50 transition disabled:opacity-60"
      >
        {working ? 'Preparing PDF...' : 'Download PDF'}
      </button>
      {working && (
        <p className="text-xs text-indigo-300" role="status">
          This can take a few seconds the first time.
        </p>
      )}
      {state.kind === 'failed' && (
        <p role="alert" className="text-xs text-amber-200 flex items-center gap-2">
          <span>{state.message}</span>
          <button
            type="button"
            onClick={() => void download()}
            className="underline hover:no-underline font-medium"
          >
            Try again
          </button>
        </p>
      )}
    </div>
  )
}

function messageFor(status: number): string {
  if (status === 404) return 'This resume could not be found.'
  if (status === 401) return 'Please sign in again.'
  if (status === 503) return 'PDF export is unavailable right now.'
  return 'Could not build the PDF.'
}
