'use client'

import { useCallback, useRef, useState } from 'react'
import Link from 'next/link'
import { filenameFromDisposition } from '@/lib/resume/export/filename'
import { canExportPdf } from '@/lib/resume/entitlement'

/**
 * Download the finished resume, in either format.
 *
 * ONE COMPONENT, TWO FORMATS. PDF and DOCX differ only in which endpoint is
 * called and what the file is named -- the entitlement, the pending state, the
 * failure handling and the filename-from-header rule are identical, and a
 * second copy of them would be a second place for them to drift.
 *
 * The file is generated by the server, from the stored resume. This component
 * sends one id and receives bytes -- it never builds HTML, never names the
 * file, and never decides what the document contains. The filename comes from
 * the response's Content-Disposition, which the route sanitises; constructing
 * one here would duplicate that sanitisation and eventually diverge from it.
 *
 * Cold-starting Chromium takes seconds, so the pending state is not decoration:
 * without it a person clicks twice and waits for two exports.
 */

type Format = 'pdf' | 'docx'

const ENDPOINTS: Record<Format, string> = {
  pdf: '/api/resume-v2/export/pdf',
  docx: '/api/resume-v2/export/docx',
}
const LABELS: Record<Format, string> = { pdf: 'Download PDF', docx: 'Download Word' }

type State =
  | { readonly kind: 'idle' }
  | { readonly kind: 'working' }
  | { readonly kind: 'failed'; readonly message: string }

export default function ExportMenu({
  resumeId,
  tier,
  disabled,
}: {
  resumeId: string
  /** Presentation only. The route refuses a non-Ultimate caller regardless. */
  tier: string
  disabled?: boolean
}) {
  const [state, setState] = useState<State>({ kind: 'idle' })
  const [busyFormat, setBusyFormat] = useState<Format | null>(null)
  const inFlight = useRef(false)

  const download = useCallback(async (format: Format) => {
    if (inFlight.current) return
    inFlight.current = true
    setBusyFormat(format)
    setState({ kind: 'working' })

    let objectUrl: string | null = null
    try {
      const res = await fetch(ENDPOINTS[format], {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: resumeId }),
      })

      if (!res.ok) {
        setState({ kind: 'failed', message: messageFor(res.status) })
        return
      }

      const blob = await res.blob()
      const filename = filenameFromDisposition(res.headers.get('Content-Disposition'))

      objectUrl = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = objectUrl
      link.download = filename
      document.body.appendChild(link)
      link.click()
      link.remove()
      setState({ kind: 'idle' })
    } catch {
      setState({ kind: 'failed', message: 'Could not reach the server.' })
    } finally {
      // Revoked later, not synchronously: revoking immediately can cancel the
      // download in Safari before it has finished reading the blob.
      if (objectUrl) {
        const url = objectUrl
        setTimeout(() => URL.revokeObjectURL(url), 30_000)
      }
      inFlight.current = false
      setBusyFormat(null)
    }
  }, [resumeId])

  const working = state.kind === 'working'

  // Below Ultimate the button is replaced rather than disabled: a greyed-out
  // control with no explanation reads as a bug, and the applicant needs to know
  // this is a plan boundary, not a broken download. The server refuses anyway.
  if (!canExportPdf(tier)) {
    return (
      <div className="flex flex-col items-start sm:items-end gap-1">
        <Link
          href="/pricing"
          className="px-4 py-2 text-sm font-semibold rounded-xl border border-amber-300/50 bg-amber-400/15 text-amber-100 hover:bg-amber-400/25 transition"
        >
          Upgrade to download
        </Link>
        <p className="text-xs text-indigo-300">
          Building and previewing are included. Ultimate adds the finished file.
        </p>
      </div>
    )
  }

  return (
    <div className="flex flex-col items-start sm:items-end gap-1">
      <div className="flex flex-wrap gap-2">
        {(['pdf', 'docx'] as const).map((format) => (
          <button
            key={format}
            type="button"
            onClick={() => void download(format)}
            disabled={working || disabled}
            aria-busy={working && busyFormat === format}
            className="px-4 py-2 text-sm font-semibold rounded-xl bg-white text-indigo-900 hover:bg-indigo-50 transition disabled:opacity-60"
          >
            {working && busyFormat === format ? 'Preparing...' : LABELS[format]}
          </button>
        ))}
      </div>
      {working && (
        <p className="text-xs text-indigo-300" role="status">
          This can take a few seconds the first time.
        </p>
      )}
      {state.kind === 'failed' && (
        <p role="alert" className="text-xs text-amber-200 flex items-center gap-2">
          <span>{state.message}</span>
          <button
            type="button"
            onClick={() => void download(busyFormat ?? 'pdf')}
            className="underline hover:no-underline font-medium"
          >
            Try again
          </button>
        </p>
      )}
    </div>
  )
}

function messageFor(status: number): string {
  if (status === 404) return 'This resume could not be found.'
  if (status === 401) return 'Please sign in again.'
  if (status === 503) return 'PDF export is unavailable right now.'
  return 'Could not build the PDF.'
}
