'use client'

import { useCallback, useRef, useState } from 'react'
import { ChevronDown, Download, FileDown, FileText } from 'lucide-react'
import { filenameFromDisposition } from '@/lib/resume/export/filename'
import { describePageSpan } from '@/lib/resume/document/pages'
import type { PageSpan } from '@/lib/resume/document/pages'
import { downloadNeedsUpgrade } from '@/lib/resume/studio/outputLock'
import { Button, IconButton, Menu, MenuItem, MenuLabel } from '../ui'
import UpgradeDialog from './UpgradeDialog'

/**
 * Download the finished resume, in either format.
 *
 * ONE COMPONENT, TWO FORMATS. PDF and DOCX differ only in which endpoint is
 * called and what the file is named -- the entitlement, the pending state, the
 * failure handling and the filename-from-header rule are identical, and a
 * second copy of them would be a second place for them to drift. On screen
 * that is one Download control with the format in its menu.
 *
 * The file is generated by the server, from the stored resume. This component
 * sends one id and receives bytes -- it never builds HTML, never names the
 * file, and never decides what the document contains. The filename comes from
 * the response's Content-Disposition, which the route sanitises; constructing
 * one here would duplicate that sanitisation and eventually diverge from it.
 *
 * Cold-starting Chromium takes seconds, so the pending state is not decoration:
 * without it a person clicks twice and waits for two exports.
 *
 * THE CONTROL LOOKS THE SAME FOR EVERY TIER. It used to be replaced by
 * "Upgrade to download" before anyone had touched it, which asked for money
 * before the applicant could see what they had built. Now everyone builds,
 * everyone previews, and a tier that cannot download is told so when they
 * choose a format -- by the modal, not by a disabled button. The routes refuse
 * the export regardless; see lib/resume/entitlement.ts.
 */

type Format = 'pdf' | 'docx'

const ENDPOINTS: Record<Format, string> = {
  pdf: '/api/resume-v2/export/pdf',
  docx: '/api/resume-v2/export/docx',
}
const LABELS: Record<Format, string> = { pdf: 'PDF document', docx: 'Word document' }
const EXTENSIONS: Record<Format, string> = { pdf: '.pdf', docx: '.docx' }

type State =
  | { readonly kind: 'idle' }
  | { readonly kind: 'working' }
  | { readonly kind: 'failed'; readonly message: string }

export default function ExportMenu({
  resumeId,
  tier,
  disabled,
  pageSpan,
  compact = false,
  onNotNow,
  onUpgrade,
}: {
  resumeId: string
  /** Presentation only. The route refuses a non-Ultimate caller regardless. */
  tier: string
  disabled?: boolean
  /**
   * One page or more, as measured by the preview. Display only -- it is never
   * sent anywhere, and the file is built from the stored resume as always.
   */
  pageSpan?: PageSpan | null
  /** Phone toolbar: an icon-sized control. */
  compact?: boolean
  /**
   * The applicant answered "Not now" at the upgrade modal. Locks the finished
   * output -- closing the modal any other way must not call this.
   * See lib/resume/studio/outputLock.ts.
   */
  onNotNow?: () => void
  /**
   * The applicant answered "Upgrade to Ultimate". Locks the finished output
   * too, and resolves only once that answer is stored, because this one leaves
   * the page. Closing the modal any other way must not call it either.
   */
  onUpgrade?: () => Promise<boolean>
}) {
  const [state, setState] = useState<State>({ kind: 'idle' })
  const [upgrading, setUpgrading] = useState(false)
  const [busyFormat, setBusyFormat] = useState<Format | null>(null)
  const inFlight = useRef(false)

  const download = useCallback(async (format: Format) => {
    if (inFlight.current) return
    inFlight.current = true
    setBusyFormat(format)
    setState({ kind: 'working' })

    let objectUrl: string | null = null
    try {
      const res = await fetch(ENDPOINTS[format], {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: resumeId }),
      })

      if (!res.ok) {
        setState({ kind: 'failed', message: messageFor(res.status) })
        return
      }

      const blob = await res.blob()
      const filename = filenameFromDisposition(res.headers.get('Content-Disposition'))

      objectUrl = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = objectUrl
      link.download = filename
      document.body.appendChild(link)
      link.click()
      link.remove()
      setState({ kind: 'idle' })
    } catch {
      setState({ kind: 'failed', message: 'Could not reach the server.' })
    } finally {
      // Revoked later, not synchronously: revoking immediately can cancel the
      // download in Safari before it has finished reading the blob.
      if (objectUrl) {
        const url = objectUrl
        setTimeout(() => URL.revokeObjectURL(url), 30_000)
      }
      inFlight.current = false
      setBusyFormat(null)
    }
  }, [resumeId])

  const working = state.kind === 'working'

  // A tier that cannot download never reaches `download`: choosing a format
  // opens the upgrade modal and nothing is requested. The routes refuse it too.
  const choose = (format: Format) => {
    if (downloadNeedsUpgrade(tier)) {
      setUpgrading(true)
      return
    }
    void download(format)
  }

  const blocked = working || Boolean(disabled)
  const waitingNote = disabled && !working ? 'Waiting for your latest edits to save' : undefined

  return (
    <div className="relative">
      <Menu
        label="Download format"
        trigger={(trigger) =>
          compact ? (
            <IconButton
              {...trigger}
              icon={Download}
              label={working ? 'Preparing download' : 'Download'}
              size="touch"
              disabled={blocked}
              aria-busy={working}
            />
          ) : (
            <Button
              {...trigger}
              variant="primary"
              icon={Download}
              trailingIcon={ChevronDown}
              disabled={blocked}
              aria-busy={working}
              title={waitingNote}
            >
              {working ? 'Preparing...' : 'Download'}
            </Button>
          )
        }
      >
        <MenuLabel>Download your saved resume</MenuLabel>
        {(['pdf', 'docx'] as const).map((format) => (
          <MenuItem
            key={format}
            icon={format === 'pdf' ? FileText : FileDown}
            // Only the PDF: it is the format whose pages are fixed. Word
            // repaginates in whatever application opens it, so claiming a page
            // count there would be a guess about someone else's software.
            hint={format === 'pdf' && pageSpan ? `PDF · ${describePageSpan(pageSpan)}` : EXTENSIONS[format]}
            onSelect={() => choose(format)}
          >
            {LABELS[format]}
          </MenuItem>
        ))}
      </Menu>

      {/* Upgrade deliberately leaves the modal open: it shows that the answer
          is being stored, and closing it early would flash the unlocked
          preview behind it on the way out. */}
      <UpgradeDialog
        open={upgrading}
        onClose={() => setUpgrading(false)}
        onNotNow={() => {
          setUpgrading(false)
          onNotNow?.()
        }}
        onUpgrade={onUpgrade}
      />

      {(working || state.kind === 'failed') && (
        <div className="absolute right-0 top-full z-40 mt-2 w-max max-w-[18rem] rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs shadow-lg">
          {working && (
            <p className="text-slate-600" role="status">
              This can take a few seconds the first time.
            </p>
          )}
          {state.kind === 'failed' && (
            <p role="alert" className="flex items-center gap-2 text-amber-800">
              <span>{state.message}</span>
              <button
                type="button"
                onClick={() => void download(busyFormat ?? 'pdf')}
                className="font-medium underline hover:no-underline"
              >
                Try again
              </button>
            </p>
          )}
        </div>
      )}
    </div>
  )
}

function messageFor(status: number): string {
  if (status === 404) return 'This resume could not be found.'
  if (status === 401) return 'Please sign in again.'
  if (status === 503) return 'PDF export is unavailable right now.'
  return 'Could not build the PDF.'
}
